#pragma once

enum DIRECTION	{ DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };

enum  OBJID     {  OBJ_PLAYER, OBJ_BULLET, OBJ_BLOCK, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum SCENEID	{ SC_LOGO, SC_MENU, SC_STAGE, SC_EDIT, SC_FARM, SC_END };

enum RENDERID	{ RENDER_BACK, RENDER_GAMEOBJECT, RENDER_UI, RENDER_END };

// 최대 32개 채널까지 동시 재생이 가능
enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER,  MAXCHANNEL };

enum BLOCK_TYPE { BASIC_BLOCK, FINISH_BLOCK, END_BLOCK };
